"""Loads data/catalog.toml and checks it is self-consistent before anything touches InvenTree."""

import os
import re
import tomllib

from .settings import CATALOG_PATH, DATA_DIR

FIELD_TYPES = {"TEXT", "NUMBER", "OPTION", "BOOLEAN"}
LABEL_SIZES = ("large", "standard", "small", "none")
KINDS = ("categories", "fields", "tags", "locations", "models")


class CatalogError(Exception):
    pass


def load_toml(path):
    try:
        with open(path, "rb") as handle:
            return tomllib.load(handle)
    except FileNotFoundError:
        raise CatalogError(f"{path} not found")
    except tomllib.TOMLDecodeError as error:
        raise CatalogError(f"{path}: {error}")


def load_catalog(path=CATALOG_PATH):
    raw = load_toml(path)
    taxonomy = {kind: {entry["name"].lower(): entry for entry in raw.get(kind, [])} for kind in KINDS}
    validate_categories(taxonomy)
    validate_fields(taxonomy)
    validate_locations(taxonomy)
    for model in taxonomy["models"].values():
        validate_model(taxonomy, model)
    return taxonomy


def require(taxonomy, kind, name, context):
    entry = taxonomy[kind].get(str(name).lower())
    if entry is None:
        raise CatalogError(f"{context}: '{name}' is not declared under [[{kind}]] in data/catalog.toml")
    return entry


def validate_label(label, context):
    if label is not None and label not in LABEL_SIZES:
        raise CatalogError(f"{context}: label must be one of {', '.join(LABEL_SIZES)}, not '{label}'")


def validate_categories(taxonomy):
    for category in taxonomy["categories"].values():
        context = f"category '{category['name']}'"
        validate_label(category.get("label"), context)
        if not category.get("placement"):
            raise CatalogError(f"{context}: needs a label placement")
        for rule in category.get("label_rules", []):
            validate_label(rule.get("label"), context)
            if not rule.get("when"):
                raise CatalogError(f"{context}: a label rule needs a 'when'")
            for name in rule["when"]:
                require(taxonomy, "fields", name, context)
        for segment in category.get("part_description", []):
            for name, _ in placeholders(segment):
                require(taxonomy, "fields", name, context)


def validate_fields(taxonomy):
    for field in taxonomy["fields"].values():
        context = f"field '{field['name']}'"
        if field.get("type", "TEXT") not in FIELD_TYPES:
            raise CatalogError(f"{context}: unknown type {field.get('type')}")
        if field.get("type") == "OPTION" and not field.get("options"):
            raise CatalogError(f"{context}: OPTION fields need options")
        if any("," in option for option in field.get("options", [])):
            raise CatalogError(f"{context}: options cannot contain commas")
        for category in field.get("categories", []):
            require(taxonomy, "categories", category, context)
        uncovered = set(taxonomy["categories"]) - {name.lower() for name in field.get("categories", [])}
        if field.get("generated") and uncovered:
            raise CatalogError(f"{context}: is generated for every model, so it needs every category; missing {', '.join(sorted(uncovered))}")


def validate_locations(taxonomy):
    for location in taxonomy["locations"].values():
        if location.get("parent"):
            require(taxonomy, "locations", location["parent"], f"location '{location['name']}'")


def validate_model(taxonomy, model):
    context = f"model '{model['name']}'"
    category = require(taxonomy, "categories", model["category"], context)
    if model.get("render"):
        validate_render(model, context)
    elif model.get("image") and not os.path.isfile(model_image_path(model)):
        raise CatalogError(f"{context}: image data/{model['image']} not found")
    validate_label(model.get("label"), context)
    for tag in model.get("tags", []):
        require(taxonomy, "tags", tag, context)
    values = model.get("fields", {})
    for name, value in values.items():
        if require(taxonomy, "fields", name, context).get("generated"):
            raise CatalogError(f"{context}: '{name}' is generated by the tool, set 'placement' on the model instead")
        validate_field_value(taxonomy, category, name, value, context)
    for field in fields_of(taxonomy, category):
        if field.get("required") and field["name"] not in values:
            raise CatalogError(f"{context}: required field '{field['name']}' is missing")


def validate_render(model, context):
    """A rendered model writes its own image, so the file may not exist before the first `previews`."""
    if not str(model.get("image", "")).startswith("images/") or not model["image"].endswith(".png"):
        raise CatalogError(f"{context}: a rendered model needs image = \"images/<name>.png\"")
    if "Design source" not in model.get("fields", {}):
        raise CatalogError(f"{context}: a rendered model needs its 'Design source'")
    if not all(isinstance(path, str) for path in model["render"]):
        raise CatalogError(f"{context}: render lists export paths inside the design folder")


def fields_of(taxonomy, category):
    return [field for field in taxonomy["fields"].values()
            if category["name"].lower() in (name.lower() for name in field.get("categories", []))]


def validate_field_value(taxonomy, category, name, value, context):
    field = require(taxonomy, "fields", name, context)
    if field not in fields_of(taxonomy, category):
        raise CatalogError(f"{context}: field '{name}' does not apply to category '{category['name']}'")
    kind = field.get("type", "TEXT")
    if kind == "NUMBER" and (isinstance(value, bool) or not isinstance(value, (int, float))):
        raise CatalogError(f"{context}: '{name}' must be a number, not {value!r}")
    if kind == "BOOLEAN" and not isinstance(value, bool):
        raise CatalogError(f"{context}: '{name}' must be true or false, not {value!r}")
    if kind == "OPTION" and value not in field["options"]:
        raise CatalogError(f"{context}: '{name}' must be one of {field['options']}, not {value!r}")
    if kind == "TEXT" and not isinstance(value, str):
        raise CatalogError(f"{context}: '{name}' must be text, not {value!r}")


def model_image_path(model):
    return os.path.join(DATA_DIR, model["image"]) if model.get("image") else None


SOLDERED_PLACEMENT = "No label: soldered, found through the board it sits on."
PLACEHOLDER = re.compile(r"\{([^}|]+)(?:\|(\w+))?\}")


def category_of(taxonomy, model):
    return require(taxonomy, "categories", model["category"], f"model '{model['name']}'")


def is_soldered(model):
    return model.get("fields", {}).get("Soldered") is True


def matching_rule(taxonomy, model):
    """The category's first label rule whose `when` matches the model's field values; a list in `when`
    means any of them."""
    values = model.get("fields", {})
    for rule in category_of(taxonomy, model).get("label_rules", []):
        if all(values.get(name) in (wanted if isinstance(wanted, list) else [wanted])
               for name, wanted in rule["when"].items()):
            return rule
    return {}


def label_size(taxonomy, model, override=None):
    """An asset's own label, else its model's, else none for soldered parts, else the category's matching
    rule, else the category's."""
    if override:
        return override
    if model.get("label"):
        return model["label"]
    if is_soldered(model):
        return "none"
    return matching_rule(taxonomy, model).get("label") or category_of(taxonomy, model).get("label", "standard")


def label_placement(taxonomy, model):
    if model.get("placement"):
        return model["placement"]
    if is_soldered(model) and not model.get("label"):
        return SOLDERED_PLACEMENT
    return matching_rule(taxonomy, model).get("placement") or category_of(taxonomy, model)["placement"]


def placeholders(segment):
    return PLACEHOLDER.findall(segment)


def value_text(value, style):
    if style == "size":
        if value >= 1000:
            return f"{number_text(value / 1000)} TB"
        return f"{number_text(value * 1024)} MB" if value < 1 else f"{number_text(value)} GB"
    return number_text(value) if isinstance(value, (int, float)) else str(value)


def number_text(value):
    return str(int(value)) if isinstance(value, float) and value.is_integer() else str(value)


def render_segment(segment, values):
    """None when a field the segment needs is missing, so the segment drops out; `|if` shows a segment
    only while its boolean is true and prints nothing itself."""
    def substitute(match):
        name, style = match.group(1), match.group(2)
        value = values.get(name)
        if value is None or value is False:
            raise LookupError(name)
        return "" if style == "if" else value_text(value, style)
    try:
        return PLACEHOLDER.sub(substitute, segment)
    except LookupError:
        return None


def part_description(taxonomy, model):
    """The model's own description, else its category's template rendered from its fields."""
    if model.get("description"):
        return model["description"]
    segments = category_of(taxonomy, model).get("part_description", [])
    text = "".join(rendered for rendered in (render_segment(segment, model.get("fields", {})) for segment in segments)
                   if rendered is not None).strip(" ,")
    return text[:1].upper() + text[1:]


def part_keywords(model):
    """InvenTree's search covers keywords but not parameters, so every field value goes in here."""
    words = []
    for value in model.get("fields", {}).values():
        if not isinstance(value, bool):
            text = value_text(value, None)
            if text not in words:
                words.append(text)
    return " ".join(words)[:250]
